#topics
base_topic: /base_controller/base_status

imu_topic: /imu #/imu/data_raw
imu_filter_topic: /imu/data #NOT USED

image_topic: /camera/color/image_raw
depth_topic: /camera/depth/color/points
camera_laser_filter: /scan_pcl_filtered #NOT USED

rplidar_topic: /scan
rplidar_filter_topic: /scan_filtered #NOT USED

rloc_odom_topic: /odometry/filtered_odom
rloc_world_topic: /odometry/filtered_world


webserver_topic: /webserver_status
agent_topic: /agent_status
dbus_topic: /connection_status
